# **Entrenamiento de Modelo**


---

Importar librerías

In [ ]:
import pandas as pd
import joblib

from scipy import sparse

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

Cargar datos preparados

In [ ]:
X_train = sparse.load_npz("X_train_tfidf.npz")
X_test = sparse.load_npz("X_test_tfidf.npz")

In [ ]:
y_train = pd.read_csv("y_train.csv").squeeze()
y_test = pd.read_csv("y_test.csv").squeeze()

In [ ]:
encoder = joblib.load("label_encoder.pkl")

Verificar que todo cargó correctamente

In [ ]:
print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(6400, 1243)
(1600, 1243)
(6400,)
(1600,)

Creamos el modelo

In [ ]:
modelo = LogisticRegression(
    random_state=42,
    max_iter=1000
)

**Entrenamiento**

In [ ]:
modelo.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42)

Hacer predicciones

In [ ]:
y_pred = modelo.predict(X_test)

Medir Presición (Accuracy)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")

Accuracy: 0.9563

**Reporte de clasificación**

In [ ]:
print(
    classification_report(
        y_test,
        y_pred,
        target_names=encoder.classes_
    )
)

              precision    recall  f1-score   support

Alimentación       0.85      0.98      0.91       320
     Compras       0.99      0.95      0.97       280
   Educación       1.00      0.92      0.96        60
        Ocio       1.00      0.99      0.99       180
       Otros       1.00      0.93      0.96        40
       Salud       1.00      0.98      0.99       140
   Servicios       0.99      0.89      0.94       240
  Transporte       0.97      0.95      0.96       240
    Vivienda       0.98      1.00      0.99       100

    accuracy                           0.96      1600
   macro avg       0.98      0.95      0.96      1600
weighted avg       0.96      0.96      0.96      1600

Guardamos modelo

In [ ]:
joblib.dump(modelo, "modelo_logistic_regression.pkl")

['modelo_logistic_regression.pkl']

## Entrenamiento de LinearSVC

Importamos librerias

In [ ]:
from sklearn.svm import LinearSVC

Creamos el modelo

In [ ]:
modelo_svc = LinearSVC(
    random_state=42
)

Entrenamos el modelo

In [ ]:
modelo_svc.fit(X_train, y_train)

LinearSVC(random_state=42)

Predicciones del modelo

In [ ]:
y_pred_svc = modelo_svc.predict(X_test)

Presición (Accuracy)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_svc = accuracy_score(y_test, y_pred_svc)

print(f"Accuracy LinearSVC: {accuracy_svc:.4f}")

Accuracy LinearSVC: 0.9606

Reporte de clasificación

In [ ]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        y_pred_svc,
        target_names=encoder.classes_
    )
)

              precision    recall  f1-score   support

Alimentación       0.85      1.00      0.92       320
     Compras       0.99      0.95      0.97       280
   Educación       1.00      0.92      0.96        60
        Ocio       1.00      0.99      0.99       180
       Otros       1.00      0.93      0.96        40
       Salud       1.00      0.99      0.99       140
   Servicios       0.99      0.89      0.94       240
  Transporte       1.00      0.96      0.98       240
    Vivienda       0.98      1.00      0.99       100

    accuracy                           0.96      1600
   macro avg       0.98      0.96      0.97      1600
weighted avg       0.97      0.96      0.96      1600

**Tabla comparativa entre ambos modelos**

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

resultados = pd.DataFrame({
    "Modelo": [
        "Regresión Logística",
        "LinearSVC"
    ],
    "Accuracy": [
        accuracy_score(y_test, y_pred),
        accuracy_score(y_test, y_pred_svc)
    ],
    "Precision Macro": [
        precision_score(y_test, y_pred, average="macro"),
        precision_score(y_test, y_pred_svc, average="macro")
    ],
    "Recall Macro": [
        recall_score(y_test, y_pred, average="macro"),
        recall_score(y_test, y_pred_svc, average="macro")
    ],
    "F1 Macro": [
        f1_score(y_test, y_pred, average="macro"),
        f1_score(y_test, y_pred_svc, average="macro")
    ]
})

resultados = resultados.round(4)

resultados

                Modelo  Accuracy  Precision Macro  Recall Macro  F1 Macro
0  Regresión Logística    0.9562           0.9754        0.9541    0.9635
1            LinearSVC    0.9606           0.9786        0.9570    0.9665

Guardamos modelo SVC

In [ ]:
joblib.dump(modelo_svc, "modelo_linear_svc.pkl")

['modelo_linear_svc.pkl']

## **Multinomial Naive Bayes**

---

Importar librerias

In [ ]:
from sklearn.naive_bayes import MultinomialNB

Crear el modelo

In [ ]:
modelo_nb = MultinomialNB()

Entrenamiento

In [ ]:
modelo_nb.fit(X_train, y_train)

MultinomialNB()

Predicciones

In [ ]:
y_pred_nb = modelo_nb.predict(X_test)

Presición (Accuracy)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_nb = accuracy_score(y_test, y_pred_nb)

print(f"Accuracy Naive Bayes: {accuracy_nb:.4f}")

Accuracy Naive Bayes: 0.9431

Reporte de clasificación

In [ ]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        y_pred_nb,
        target_names=encoder.classes_
    )
)

              precision    recall  f1-score   support

Alimentación       0.83      0.94      0.88       320
     Compras       0.95      0.96      0.96       280
   Educación       1.00      0.83      0.91        60
        Ocio       0.99      0.99      0.99       180
       Otros       1.00      0.90      0.95        40
       Salud       1.00      0.98      0.99       140
   Servicios       0.99      0.88      0.93       240
  Transporte       0.95      0.95      0.95       240
    Vivienda       1.00      0.98      0.99       100

    accuracy                           0.94      1600
   macro avg       0.97      0.94      0.95      1600
weighted avg       0.95      0.94      0.94      1600

Tabla comparativa de los 3 modelos

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

resultados = pd.DataFrame({
    "Modelo": [
        "Regresión Logística",
        "Linear SVC",
        "Multinomial NB"
    ],
    "Accuracy": [
        accuracy_score(y_test, y_pred),
        accuracy_score(y_test, y_pred_svc),
        accuracy_score(y_test, y_pred_nb)
    ],
    "Precision Macro": [
        precision_score(y_test, y_pred, average="macro"),
        precision_score(y_test, y_pred_svc, average="macro"),
        precision_score(y_test, y_pred_nb, average="macro")
    ],
    "Recall Macro": [
        recall_score(y_test, y_pred, average="macro"),
        recall_score(y_test, y_pred_svc, average="macro"),
        recall_score(y_test, y_pred_nb, average="macro")
    ],
    "F1 Macro": [
        f1_score(y_test, y_pred, average="macro"),
        f1_score(y_test, y_pred_svc, average="macro"),
        f1_score(y_test, y_pred_nb, average="macro")
    ]
})

resultados = resultados.round(4)

resultados.sort_values("F1 Macro", ascending=False)

                Modelo  Accuracy  Precision Macro  Recall Macro  F1 Macro
1           Linear SVC    0.9606           0.9786        0.9570    0.9665
0  Regresión Logística    0.9562           0.9754        0.9541    0.9635
2       Multinomial NB    0.9431           0.9683        0.9352    0.9498